const responseObj = {
    hello: "Hey! How may I help you?",
    hey: "Hello! What's Up",
    hi: "Hi! How may I help you?",
    today: new Date().toDateString(),
    time: new Date().toLocaleTimeString(),
    xuan: "Yu Xuan is pweety and cute!!!!",
    moon: "i like her :D",
    thanks: "you are welcome :D",
    ":)": ":D",
    "thank you": "my pleasure :3",
    "excuse me": "Yes! How may I help you?",
    "black panther price" : "RM18",
    "aladdin price" : "RM18",
    "frozen 2 price" : "RM18",
    "inside out price" : "RM18",
    "encanto price" : "RM18",
    "raya and the last dragon price" : "RM18",
    "mary poppins returns price" : "RM18",
    "doctor strange price" : "RM18",
    "cruella price" : "RM18",
    "mulan price" : "RM18",
    "squid game price" : "RM18",
    "black adam price" : "RM18",
    "train to busan price" : "RM18",
    "2012 price" : "RM18",
    "3 idiots" : "RM18",
    "black panther showtime" : "00:00, 15:00, 18:00, and 21:00",
    "aladdin showtime" : "00:00, 03:00, 18:00, and 21:00",
    "frozen 2 showtime" : "00:00, 03:00, 06:00, and 21:00",
    "inside out showtime" : "03:00, 06:00, and 09:00",
    "encanto showtime" : "06:00, 09:00, and 12:00",
    "raya and the last dragon showtime" : "09:00, 12:00, and 15:00",
    "mary poppins returns showtime" : "12:00, 15:00, and 18:00",
    "doctor strange showtime" : "15:00, 18:00, and 21:00",
    "cruella showtime" : "00:00, 18:00, and 21:00",
    "mulan showtime" : "00:00, 03:00, and 21:00",
    "squid game showtime" : "00:00, 03:00, and 06:00",
    "black adam showtime" : "03:00, 06:00, and 09:00",
    "train to busan showtime" : "06:00, 09:00, and 12:00",
    "2012 showtime" : "09:00, 12:00, and 15:00",
    "3 idiots showtime" : "12:00, 15:00, and 18:00",
    "the conjuring release date" : "26 March 2023",
    "interstellar release date" : "26 October 2023",
    "jurassic world release date" : "11 June 2023",
    "alien release date" : "6 September 2023",
    "moonfall release date" : "3 March 2023",
    "r.i.p.d release date" : "19 July 2023",
    "harry potter release date" : "22 November 2023",
    "spider man release date" : "17 December 2023",
    "the shawshank redemption release date" : "22 September 2023",
    "the morbius release date" : "1 April 2023",
    "food" : "popcorn, nachos, fries, and others",
    "snacks" : "popcorn, nachos, fries, and others",
    "beverages" : "iced lemon tea, pear tea, and others",
    "drinks" : "iced lemon tea, pear tea, and others",
    "popcorn price" : "RM 10",
    "nachos price" : "RM 12",
    "chicken nuggets price" : "RM 15",
    "fries price" : "RM 8",
    "hotdog price" : "RM 10",
    "potato chips price" : "RM 8", 
    "chocolate chip cookies price" : "RM 15 (5 Pcs)",
    "berry cupcake price" : "RM 8",
    "mango smoothie price" : "RM 18",
    "watermelon smoothie price" : "RM 18",
    "blueberry smoothie price" : "RM 18",
    "brown sugar milk tea price" : "RM 15",
    "ice blended chocolate price" : "RM 15",
    "iced lemon tea price" : "RM 10",
    "caramel macchiato price" : "RM 15",
    "pear tea price" : "RM 10",
    "where is the cinema" : "Penang, Kuala Lumpur, Selangor, Johor",
    "location" : "Penang, Kuala Lumpur, Selangor, Johor",
};